# Generated by Django 5.0.1 on 2024-11-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
        ('assessments', '0019_coursefinalscore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='average_score',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                default=None, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='assessments.CourseFinalScore'
            ),
        ),
        migrations.AlterModelTable(
            name='performanceanalytics',
            table=None,
        ),
    ]
