# Generated by Django 5.0.1 on 2024-11-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_alter_performanceanalytics_table'),
        ('assessments', '0019_coursefinalscore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='average_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.coursefinalscore'),
        ),
    ]
