# Generated by Django 5.0.1 on 2024-11-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_alter_performanceanalytics_average_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='performanceanalytics',
            table='achievement_performance',
        ),
    ]
