# Generated by Django 5.0.1 on 2024-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0007_rename_average_score_performanceanalytics_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
