# Generated by Django 5.0.1 on 2024-11-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_alter_performanceanalytics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='completion_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
