# Generated by Django 5.0.1 on 2024-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0011_rename_average_score_performanceanalytics_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
