# Generated by Django 5.0.1 on 2024-11-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0012_alter_performanceanalytics_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='performanceanalytics',
            table='achievement_performanceanalytics',
        ),
    ]
