# Generated by Django 5.0.1 on 2024-11-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0014_rename_score_performanceanalytics_average_score'),
        ('assessments', '0021_alter_coursefinalscore_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceanalytics',
            name='average_score',
        ),
        migrations.AddField(
            model_name='performanceanalytics',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.coursefinalscore'),
        ),
    ]
