# Generated by Django 5.0.1 on 2024-11-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0016_alter_performanceanalytics_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
