# Generated by Django 5.0.1 on 2024-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0017_alter_performanceanalytics_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
